name: Build rel APK

on:
  push:
  pull_request:
  workflow_call:
  workflow_dispatch:

jobs:
  build-rel-apk:
    runs-on: ubuntu-latest
    continue-on-error: true
    steps:
      - name: Check out repository
        uses: actions/checkout@v4
        with:
          submodules: true
      - uses: actions/setup-java@v4
        with:
          distribution: "zulu"
          java-version: 21
      - uses: gradle/actions/setup-gradle@v3
        with:
          cache-encryption-key: Da25KUVSE5jbGds2zXmfXw==
          gradle-home-cache-cleanup: true
      - name: Build rel APK
        run: ./gradlew clean app:assembleRelease
      - name: Rename APK
        run: mv app/build/outputs/apk/app/release/Lawnicons*.apk app/build/outputs/apk/app/release/Lawniconsr.apk
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: Lawnicons
          path: app/build/outputs/apk/app/release/*.apk
